package de.spdmc.frodo.enumerations;

public class Enumerations {

    public enum DialogState {
        PARSE_GREETING,
        PARSE_QUERY,
        PARSE_NAME,
        NAME_REPLY,
        NAME_DECLINED,
        NAME_REASK,
        NAME_REASK2,
        QUERY_REPLY,
        NAME_WITHDRAW, // Namen widerrufen
        PARSE_FAVORITE_TYPE,
        FAVORITE_TYPE_REPLY,
        FAVORITE_TYPE_REASK,
        PARSE_GENRE,
        GREETING_REPLY,
        GENRE_REPLY,
        GENRE_FAULT_REPLY,
        PARSE_FAVORITE_ACTOR,
        FAVORITE_TYPE_FAULT_REPLY,
        FAVORITE_ACTOR_DECLINED,
        FAVORITE_ACTOR_REASK,
        FAVORITE_ACTOR_REPLY,
        RECOMMEND,
        GENRE_DECLINED,
        GENRE_REASK,
        FAVORITE_MOVIES_REASK,
        FAVORITE_MOVIES_DECLINED,
        FAVORITE_MOVIES_ASK_MORE,
        FAVORITE_ACTOR_FAULT_REPLY,
        FAVORITE_MOVIES_ASK_CONFIRM,
        PARSE_FAVORITE_MOVIE_YES_NO,
        FAVORITE_TVSHOW_REASK,
        FAVORITE_TVSHOW_DECLINED,
        FAVORITE_TVSHOW_ASK_MORE,
        FAVORITE_TVSHOW_ASK_CONFIRM,
        PARSE_FAVORITE_TVSHOW,
        PARSE_FAVORITE_TVSHOW_YES_NO,
        PARSE_RECOMMENDATION_YES_NO,
        FAVORITE_TVSHOW_IN_ADDITION,
        FAVORITE_MOVIES_IN_ADDITION,
        GOODBYE,
        PARSE_FAVORITE_MOVIE
    }

}
